---
abstract: 'fold and unfold nested hashrefs'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Fold
no_index:
  directory:
    - t
    - inc
requires:
  Moose: 0
  Sub::Exporter: 0
  perl: 5.008003
version: v0.0.1
